version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    working_dir: /var/www/html/public
    volumes:
      - ./src/public:/var/www/html/public
      - ./src/storage/app:/var/www/html/storage/app:ro
      - ./infra/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - api-network
    depends_on:
      - php-fpm
      - db
      - redis
      - prometheus
      - mailhog

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.dev.php
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php-fpm
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./infra/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - api-network

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: facilittei
      MYSQL_ROOT_PASSWORD: 4321
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./infra/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - api-network
  
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: redis
    networks:
      - api-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - api-network

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      - api-network

  mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
