global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: nginx
    scrape_interval: 5s
    static_configs:
      - targets: [ nginx:80 ]
