name: CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version to deploy"
        required: true

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Bastion
        id: bastion
        env:
          SSH_USER: ${{ secrets.EC2_USER }}
          SSH_KEY: ${{ secrets.EC2_KEY }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
          SSH_HOST_VM: ${{ secrets.EC_HOST_VM }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          cat >>~/.ssh/config <<END
          Host bastion
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/key.pem
          HOST $SSH_HOST_VM
            User $SSH_USER
            IdentityFile ~/.ssh/key.pem
            ProxyCommand ssh bastion -W %h:%p
          END
      - name: Listing files
        run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_PROXY_HOST_0 }} 'ls /home'
