name: CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version to deploy"
        required: true

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SSH into Bastion
        id: bastion
        env:
          SSH_USER: ${{ secrets.EC2_USER }}
          SSH_KEY: ${{ secrets.EC2_KEY }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          cat >>~/.ssh/config <<CFG
          Host bastion
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/key.pem
            StrictHostKeyChecking no
          CFG

      - name: Run command on Bastion server
        run: .github/workflows/deployment.sh
