name: CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version to deploy"
        required: true

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SSH key of bastion
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_KEY }}
          name: id_rsa-bastion
          known_hosts: ${{ secrets.EC2_KNOWN_HOSTS }}
          config: ${{ secrets.EC2_CONFIG }}

      - name: Install SSH key of target
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_KEY }}
          name: id_rsa-target
          known_hosts: ${{ secrets.EC2_KNOWN_HOSTS_0 }}
          config: ${{ secrets.EC2_CONFIG_0 }}

      - name: Proxy host command
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_PROXY_HOST_0 }}
          ls
