name: CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version to deploy"
        required: true

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ssh proxy command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          proxy_host: ${{ secrets.EC2_PROXY_HOST_0 }}
          proxy_username: ${{ secrets.EC2_USER }}
          proxy_key: ${{ secrets.EC2_KEY }}
          script: |
            ls -a
